<?php
//CONFIGURACIÓN PARA BOADILLA DEL MONTE
$CONTADOR=1;
$BASE_DATOS='INSCRIPCIONES_BOMO';
$URL="http://" . substr($_SERVER["HTTP_HOST"] .$_SERVER["REQUEST_URI"], 0, strrpos ( $_SERVER["HTTP_HOST"] .$_SERVER["REQUEST_URI"],  "/" ))."/comprueba.php";
$GYMKANA="BOADILLA DEL MONTE";
?>
